modLoader="javafml"
loaderVersion="[35,)"
license="LGPL-v2.1"
updateJSONURL="https://tophat.cat/santas-workshop/update.json"
issueTrackerURL="https://github.com/tophatcats-mods/santas-workshop/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/santas-workshop"
#logoFile=""
credits="ProxyNeko"
authors="ProxyNeko"

[[mods]]
modId="santasworkshop"
version="${file.jarVersion}"
displayName="santasworkshop"
description='''
The realm of santasworkshop, or at least my interpritation of it in Minecraft.
'''

[[dependencies.santasworkshop]]
modId="forge"
mandatory=true
versionRange="[35,)"
ordering="NONE"
side="BOTH"
[[dependencies.santasworkshop]]
modId="minecraft"
mandatory=true
versionRange="[1.16.4]"
ordering="NONE"
side="BOTH"